---
baseurl: 'https://ibrahimmaigablog.netlify.app/'
title: Ibrahim's Blog
theme: hugo-theme-cleanwhite
languageCode: en-us
# disqusShortname:
googleAnalytics: G-1FKN8FBX2R
preserveTaxonomyNames: true
paginate: 10
hasCJKLanguage: true
outputs:
  home:
    - HTML
    - RSS
    - Algolia
outputFormats:
  Algolia:
    baseName: algolia
    isPlainText: true
    mediaType: application/json
    notAlternative: true
markup:
  tableOfContents:
    endLevel: 2
    startLevel: 1
  highlight:
    style: dracula
  goldmark:
    renderer:
      unsafe: true
params:
  header_image: /img/background.webp
  SEOTitle: Ibrahim's Blog | Ibrahim Ma誰ga
  description: 'Ibrahim Ma誰ga is an AI Developer with extensive experience in Data Science, and Finance'
  keyword: >-
    Ibrahim Ma誰ga, AI, Artificial Intelligence, Data, Science, Cloud, Big Data, 
    Finance, Technology, Python, SQL, ETL, Developer, Blog, AWS, Git, Portfolio, Project
  slogan: 'Exploring the Frontiers of Technology to Unlock a World of Opportunity.'
  image_404: img/404-bg.jpg
  title_404: 'The future is a mystery, you've stumbled into the unknown :('
  page_view_conter: false
 # leancloud_app_id: 
 # leancloud_app_key: 
  # https://forestry.io/blog/search-with-algolia-in-hugo/
  algolia_search: true
#  algolia_appId: 
#  algolia_indexName: 
#  algolia_apiKey: 
  sidebar_about_description: 'AI Developer at Semper8 | Experienced in Data Science and Finance | Open-Source Enthusiast | Art Lover'
  sidebar_avatar: avatar.jpeg
  featured_tags: true
  featured_condition_size: 5
  ba_track_id: 
  reward: false
  reward_guide: 
  friends: false
  bookmarks: true
  about_me: true
  giscus:
    data_repo: "Ibrahim-Maiga/Blog"
    data_repo_id: "R_kgDONI6zeg"
    data_category: "Announcements"
    data_category_id: "DIC_kwDONI6zes4Cj6JF"
    data_mapping: "pathname"
    data_reactions_enabled: "1"
    data_emit_metadata: "0"
    data_theme: "light"
    data_lang: "en"
    crossorigin: "anonymous"

  # We need a proxy to access Disqus api in China
  # disqus_proxy : ''
  # disqus_site : ''
  social:
    rss: true
    email: 'imaig090@gmail.com'
    linkedin: 'www.linkedin.com/in/ibrahim-ma誰ga'
    github: 'https://github.com/Ibrahim-Maiga'  
 #   website: 'https://ibrahimmaiga.netlify.app'
 # friend_link:
 #   - title: 
 #    href: ''
 #   - title: 
 #    href: ''
 # bookmark_link:
 #   - title: 
 #     href: ''
 #   - title: 
 #     href: ''
 #   - title:
 #     href: ''
 #   - title: 
 #     href: ''
 #   - title: 
 #     href: ''
 #   - title: 
 #     href: ''
 #   - title:
 #     href: ''
#   publications:
 #   title: MY BOOKS
 #   items:
 #     - title: 
 #       image: 
 #       href: 
 #     - title: 
 #       image: 
 #       href: 
 #     - title: 
 #       image: 
 #       href: 
  addtional_menus:
    - title: READING
      href: /reading/
    - title: ARCHIVE
      href: /archive/
    - title: ABOUT
      href: /about/
  algolia:
    vars:
      - title
      - summary
      - date
      - publishdate
      - expirydate
      - permalink
    params:
      - categories
      - tags
